env_name: edge-react-example
env_deps:
  edm:
  - click
  - filetype
  - gunicorn
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
  - src_edge/src
app_deps:
- enthought_edge>=2.16.0
- appdirs
- packaging
- pip
- pyparsing
- setuptools
- six
- click
- flask>2
- gunicorn
- opencv_python
cmd_deps:
- docker
framework: react
app_id: null
