env_name: edge-streamlit-example
env_deps:
  edm:
  - click
  - oauthlib
  - pip
  - pyyaml
  - setuptools
  pip:
  - questionary
  - src_edge/src
app_deps:
- enthought_edge>=2.16.0
- appdirs
- packaging
- pip
- pyparsing
- setuptools
- six
- requests
cmd_deps:
- docker
framework: streamlit
app_id: null
