app_id: edge-streamlit-example
framework: streamlit
app_version: 1.3.0
python_version: 3.11
repository: quay.io
organisation: enthought
env_deps:
  edm:
  - click
  - enthought_edge
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
app_deps:
  edm:
  - enthought_edge>=2.16.0
  - packaging
  - pip
  - pyparsing
  - setuptools
  - six
  - requests
  pip:
  - streamlit
  - streamlit-javascript
  - streamlit-extras
cmd_deps:
- docker
exclude:
- bootstrap.py
