app_id: edge-minimal-example
framework: generic
app_version: 1.2.0
python_version: 3.11
repository: quay.io
organisation: enthought
env_deps:
  edm:
  - click
  - enthought_edge
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
app_deps:
  edm:
  - flask
  - pip
  - setuptools
  - gunicorn
  - enthought_edge
  pip: []
cmd_deps:
- docker
exclude:
- bootstrap.py
