env_name: edge-minimal-example
framework: generic
app_id: null
env_deps:
  edm:
  - click
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
  - src_edge/src
app_deps:
- flask
- setuptools
- gunicorn
- enthought_edge
cmd_deps:
- docker
exclude:
- bootstrap.py
