env_name: edge-minimal-example
env_deps:
- click
- oauthlib
- pip
- pyyaml
- questionary
- setuptools
app_deps:
- flask
- setuptools
- gunicorn
- enthought_edge
cmd_deps:
- docker
framework: generic
app_id: null
