#!/command/with-contenv sh
exec 2>&1
cd /home/app_admin
set -e
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
exec edm run -- streamlit run streamlit-app-example/app.py --server.headless true --server.port 9000
