#!/bin/sh
exec 2>&1
cd /home/app_admin
set -e
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
if [ -z $JUPYTERHUB_SERVICE_PREFIX]; then
    export STREAMLIT_BASE_URL_ARG=""
else
    export STREAMLIT_BASE_URL_ARG="--server.baseUrlPath $JUPYTERHUB_SERVICE_PREFIX"
fi
exec edm run -- streamlit run streamlit-app-example/app.py --server.headless true --server.port 9000 $STREAMLIT_BASE_URL_ARG
