name: build-example 
description: Build and Test Edge Native Example
inputs:
  component:
    description: The example to build
    required: true

runs:
  using: composite
  steps:
    - name: Setup NodeJS 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: |
          **/package-lock.json

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: |
          /tmp/.buildx-cache
        key:  ${{ runner.os }}-${{ inputs.component }}-${{ hashFiles(inputs.component) }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.component }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build and test example 
      shell: bash
      run: |
        set -e
        cd ${{ inputs.component }}
        edm run -e bootstrap -- python bootstrap.py
        edm run -e ${{ inputs.component }} -- python -m ci generate_bundle
        edm run -e ${{ inputs.component }} -- python -m ci container build
        edm run -e ${{ inputs.component }} -- python -m ci container test
        edm run -e ${{ inputs.component }} -- python -m ci preflight test

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
