env_name: edge-panel-example
env_deps:
  edm:
  - click
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
  - src_edge/src
app_deps:
- enthought_edge>=2.16.0
- appdirs
- packaging
- pip
- pyparsing
- setuptools
- six
- panel
- numpy
- pandas
- matplotlib
cmd_deps:
- docker
framework: panel
app_id: null
