app_id: edge-panel-example
framework: panel
app_version: 1.3.0
python_version: 3.11
repository: quay.io
organisation: enthought
env_deps:
  edm:
  - click
  - enthought_edge
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
app_deps:
  edm:
  - enthought_edge>=2.16.0
  - packaging
  - pip
  - pyparsing
  - setuptools
  - six
  - numpy
  - pandas
  - matplotlib
  pip:
  - panel
cmd_deps:
- docker
exclude:
- bootstrap.py
