app_id: edge-plotly-dash-example
framework: plotly-dash
app_version: 1.3.0
python_version: 3.11
repository: quay.io
organisation: enthought
env_deps:
  edm:
  - click
  - enthought_edge
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
app_deps:
  edm:
  - dash
  - enthought_edge>=2.16.0
  - packaging
  - pip
  - pyparsing
  - setuptools
  - six
  - requests
  - gunicorn
  - pandas
  - flask>2
  pip:
  - Flask-Session
cmd_deps:
- docker
exclude:
- bootstrap.py
