env_name: edge-plotly-dash-example
framework: plotly-dash
app_id: null
app_version: 1.3.0
repository: quay.io/enthought
env_deps:
  edm:
  - click
  - filetype
  - oauthlib
  - pip
  - python_dateutil
  - pyyaml
  - requests
  - setuptools
  pip:
  - questionary
  - src_edge/src
app_deps:
- enthought_edge>=2.16.0
- appdirs
- packaging
- pip
- pyparsing
- setuptools
- six
- requests
- gunicorn
- pandas
- flask>2
- dash
cmd_deps:
- docker
exclude:
- bootstrap.py
