env_name: edge-plotly-dash-example
env_deps:
- click
- oauthlib
- pip
- pyyaml
- questionary
- setuptools
app_deps:
- enthought_edge>=2.16.0
- appdirs
- packaging
- pip
- pyparsing
- setuptools
- six
- requests
- gunicorn
- pandas
- flask>2
- dash
cmd_deps:
- docker
framework: plotly-dash
app_id: null
