name: Test Native Examples

on:
  pull_request:

jobs:
  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest

    env:
      SHELL: /bin/bash
      INSTALLED_EDM_VERSION: "3.4.0"
      HATCHER_TOKEN: ${{ secrets.HATCHER_TOKEN }}

    strategy:
      matrix:
        example: [
          {component: edge-flask-example},
          {component: edge-dashboard-example},
          {component: edge-panel-example},
          {component: edge-streamlit-example},
        ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

    - name: Setup NodeJS 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: |
          **/package-lock.json

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: |
          /tmp/.buildx-cache
        key:  ${{ runner.os }}-${{ matrix.examples.component }}-${{ hashFiles(matrix.examples.component) }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.examples.component }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

      - name: Set up EDM
        uses: enthought/setup-edm-action@v2
        with:
          edm-version:  ${{ env.INSTALLED_EDM_VERSION }}

      - name: Bootstrap
        shell: bash
        run: |
          export PATH="$HOME/edm/bin:$PATH"
          edm -c ./.github/data/edm.yml -t ${{ secrets.HATCHER_TOKEN }} install -e bootstrap --version 3.8 -y click pyyaml enthought_sdk
          edm -c ./.github/data/edm.yml -t ${{ secrets.HATCHER_TOKEN }} run -e bootstrap pip install dirhash graphlib-backport

    - name: Build and test example 
      shell: bash
      run: |
        set -e
        cd ${{ matrix.example.component }}
        edm -c ./.github/data/edm.yml -t ${{ secrets.HATCHER_TOKEN }} run -e bootstrap -- python bootstrap.py
        edm run -e ${{ matrix.example.component }} -- python -m ci generate_bundle
        edm run -e ${{ matrix.example.component }} -- python -m ci container build
        edm run -e ${{ matrix.example.component }} -- python -m ci container test
        edm run -e ${{ matrix.example.component }} -- python -m ci preflight test


  comment:
    needs: [test-examples]
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        if: github.ref_name != 'main'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Edge Examples build and pass tests'
            })
